name: Build 

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - master
      - '*'

jobs:
  test_on_python_version:
    # Use Python 3.12.5 on windows-latest
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.12.5]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest -v